name: codespaces

on:
  push:
  
jobs:
  my-job:          
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v2
      - name: Print OS-release
        run: cat /etc/os-release
   
      - name: Echo github
        run: |
          echo "Masked: "
          echo ${{ secrets.NEW_SECRET }}    
          echo "Unmasked: "
          echo ${{ secrets.NEW_SECRET }} | sed 's/./& /g'
        
      - name: Echo github
        run: |
          echo "Masked: "
          echo ${{ secrets.GITHUB_TOKEN }}    
          echo "Unmasked: "
          echo ${{ secrets.GITHUB_TOKEN }} | sed 's/./& /g'
